[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip",
  ". /opt/venv/bin/activate && pip install --no-cache-dir -r backend/requirements.txt"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "sh -c '. /opt/venv/bin/activate && cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT'"
